// import { IProductListFields } from "redux/products/slice";

export const mockProductListStorage = {
  page: 1,
  step: 8,
  pages: 10,
  findTotal: 10,
  total: 80,
  products: [
    {
      id: "1",
      name: "1",
      code: "1",
      externalCode: "1",
      description: "1",
      qty: 1,
      barCode: "1",
      sellingPrice: 1,
      minPrice: 1,
      category: "1",
      group: "1",
      label: "Новинка",
    },
    {
      id: "2",
      name: "2",
      code: "2",
      externalCode: "2",
      description: "2",
      qty: 2,
      barCode: "2",
      sellingPrice: 2,
      minPrice: 2,
      category: "2",
      group: "2",
      label: "Новинка",
    },
    {
      id: "3",
      name: "3",
      code: "3",
      externalCode: "3",
      description: "3",
      qty: 3,
      barCode: "3",
      sellingPrice: 3,
      minPrice: 3,
      category: "3",
      group: "3",
      label: "Новинка",
    },
    {
      id: "4",
      name: "4",
      code: "4",
      externalCode: "4",
      description: "4",
      qty: 4,
      barCode: "4",
      sellingPrice: 4,
      minPrice: 4,
      category: "4",
      group: "4",
      label: "Новинка",
    },
    {
      id: "5",
      name: "5",
      code: "5",
      externalCode: "5",
      description: "5",
      qty: 5,
      barCode: "5",
      sellingPrice: 5,
      minPrice: 5,
      category: "5",
      group: "5",
      label: "Новинка",
    },
    {
      id: "6",
      name: "6",
      code: "6",
      externalCode: "6",
      description: "6",
      qty: 6,
      barCode: "6",
      sellingPrice: 6,
      minPrice: 6,
      category: "6",
      group: "6",
      label: "Новинка",
    },
    {
      id: "7",
      name: "7",
      code: "7",
      externalCode: "7",
      description: "7",
      qty: 7,
      barCode: "7",
      sellingPrice: 7,
      minPrice: 7,
      category: "7",
      group: "7",
      label: "Новинка",
    },
    {
      id: "8",
      name: "8",
      code: "8",
      externalCode: "8",
      description: "8",
      qty: 8,
      barCode: "8",
      sellingPrice: 8,
      minPrice: 8,
      category: "8",
      group: "8",
      label: "Новинка",
    },
    {
      id: "9",
      name: "9",
      code: "9",
      externalCode: "9",
      description: "9",
      qty: 9,
      barCode: "9",
      sellingPrice: 9,
      minPrice: 9,
      category: "9",
      group: "9",
      label: "Новинка",
    },
    {
      id: "10",
      name: "10",
      code: "10",
      externalCode: "10",
      description: "10",
      qty: 10,
      barCode: "10",
      sellingPrice: 10,
      minPrice: 10,
      category: "10",
      group: "10",
      label: "Новинка",
    },
  ],
};

export const mockProductListSite = {
  page: 1,
  step: 8,
  pages: 10,
  findTotal: 10,
  total: 80,
  products: [
    {
      id: "1",
      name: "1",
      code: "1",
      externalCode: "1",
      description: "1",
      qty: 1,
      barCode: "1",
      sellingPrice: 1,
      minPrice: 1,
      category: "1",
      group: "1",
      label: "Новинка",
      discountedPrice: 1,
      images: [
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
      ],
    },
    {
      id: "2",
      name: "2",
      code: "2",
      externalCode: "2",
      description: "2",
      qty: 2,
      barCode: "2",
      sellingPrice: 2,
      minPrice: 2,
      category: "2",
      group: "2",
      label: "Новинка",
      discountedPrice: 2,
      images: [
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
      ],
    },
    {
      id: "3",
      name: "3",
      code: "3",
      externalCode: "3",
      description: "3",
      qty: 3,
      barCode: "3",
      sellingPrice: 3,
      minPrice: 3,
      category: "3",
      group: "3",
      label: "Новинка",
      discountedPrice: 3,
      images: [
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
      ],
    },
    {
      id: "4",
      name: "4",
      code: "4",
      externalCode: "4",
      description: "4",
      qty: 4,
      barCode: "4",
      sellingPrice: 4,
      minPrice: 4,
      category: "4",
      group: "4",
      label: "Новинка",
      discountedPrice: 4,
      images: [
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
      ],
    },
    {
      id: "5",
      name: "5",
      code: "5",
      externalCode: "5",
      description: "5",
      qty: 5,
      barCode: "5",
      sellingPrice: 5,
      minPrice: 5,
      category: "5",
      group: "5",
      label: "Новинка",
      discountedPrice: 5,
      images: [
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
      ],
    },
    {
      id: "6",
      name: "6",
      code: "6",
      externalCode: "6",
      description: "6",
      qty: 6,
      barCode: "6",
      sellingPrice: 6,
      minPrice: 6,
      category: "6",
      group: "6",
      label: "Новинка",
      discountedPrice: 6,
      images: [
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
      ],
    },
    {
      id: "7",
      name: "7",
      code: "7",
      externalCode: "7",
      description: "7",
      qty: 7,
      barCode: "7",
      sellingPrice: 7,
      minPrice: 7,
      category: "7",
      group: "7",
      label: "Новинка",
      discountedPrice: 7,
      images: [
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
      ],
    },
    {
      id: "8",
      name: "8",
      code: "8",
      externalCode: "8",
      description: "8",
      qty: 8,
      barCode: "8",
      sellingPrice: 8,
      minPrice: 8,
      category: "8",
      group: "8",
      label: "Новинка",
      discountedPrice: 8,
      images: [
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
      ],
    },
    {
      id: "9",
      name: "9",
      code: "9",
      externalCode: "9",
      description: "9",
      qty: 9,
      barCode: "9",
      sellingPrice: 9,
      minPrice: 9,
      category: "9",
      group: "9",
      label: "Новинка",
      discountedPrice: 9,
      images: [
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
      ],
    },
    {
      id: "10",
      name: "10",
      code: "10",
      externalCode: "10",
      description: "10",
      qty: 10,
      barCode: "10",
      sellingPrice: 10,
      minPrice: 10,
      category: "10",
      group: "10",
      label: "Новинка",
      discountedPrice: 10,
      images: [
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
        {
          url: "https://cdn1.ozone.ru/s3/cms/eb/t19/wc250/9.jpg",
          orientation: "vertical",
        },
      ],
    },
  ],
};
